# This config file allows the GraphQL.vscode-graphql extension to provide support for graphql files.
projects:
  api:
    schema: "graphql/schema.graphql"
  admin:
    schema: "graphql/schema.graphql"
    documents: "src/js/**/*.graphql"
