name: Check schema

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/*lighthouse*.yml
      - api/**
  pull_request:
    paths:
      - .github/workflows/*lighthouse*.yml
      - api/**

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Create admin .env file, which is referenced in docker-compose
        working-directory: frontend/admin
        run: cp .env.example .env

      - name: "Build docker image: api"
        working-directory: infrastructure
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up api --detach

      - name: "Re-generate lighthouse schema"
        working-directory: infrastructure
        run: |
          docker compose exec --no-TTY api php artisan lighthouse:print-schema --write
          docker compose cp api:/var/www/html/api/storage/app/lighthouse-schema.graphql ../frontend/

      - name: Check for uncommitted changes
        id: changes
        # See: https://github.com/UnicornGlobal/has-changes-action
        uses: UnicornGlobal/has-changes-action@v1.0.12

      - name: Error if changes
        if: steps.changes.outputs.changed == 1
        # See: https://github.com/actions/github-script
        uses: actions/github-script@v5.1.0
        with:
          script: |
            core.setFailed('Please update frontend/lighthouse-schema.graphql')

      # Allows SSH access into CI environment for up to 1h.
      # Use `touch ~/continue` with session to end each one.
      # Only enable when trying to troubleshoot.
      #
      # Note: Be cautious, as secrets in environment can be compromised.
      #   Consider using in PRs from forks, without secrets available.
      #
      # See: https://github.com/lhotari/action-upterm
      - name: Create upterm session for debug
        uses: lhotari/action-upterm@v1
        if: ${{ false }}
        # if: ${{ always() }}
