name: LinkChecker

on:
  push: # only for testing on the feature branch..remove this when merging
    branches:
      - "**" # Trigger on any branch commit
  workflow_dispatch: # allows manual trigger
  schedule:
    # Every Wednesday at 2:00 AM UTC
    - cron: "0 2 * * 3"

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      # Use native docker command within docker compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
      PNPM_VERSION: "10.17.0"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run External Link Checker
        run: pnpm run check-links

      - name: Count Broken Links
        id: count
        run: |
          if [ -f external-broken-links.json ]; then
            num=$(jq length external-broken-links.json)
          else
            num=0
          fi
          echo "brokenLinksCount=$num" >> $GITHUB_OUTPUT

      - name: Upload Report Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: external-link-check-results
          path: |
            external-links.json
            external-broken-links.json
            external-link-errors.log

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: External Link Checker found *${{ steps.count.outputs.brokenLinksCount  }}* broken links in GC Talent Application."
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Artifacts",
                      "emoji": true
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
