name: Vitest

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - .github/workflows/*vitest*.yml
      - apps/**
      - packages/**
  merge_group:
    branches: [main]
jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-24.04
    env:
      PNPM_VERSION: "10.27.0"

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - uses: actions/checkout@v6

      - name: Remove unused deps
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet

      - name: "Copy .env"
        working-directory: "./apps/web"
        run: |
          cp .env.example .env

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "./.nvmrc"
          cache: pnpm

      - name: "Install dependencies: workspace"
        working-directory: ./
        run: pnpm install --frozen-lockfile

      - name: Setup
        run: |
          pnpm codegen
          pnpm intl-compile

      # Clean up any possible files taking up unnecessary space
      - name: Clean up
        run: |
          rm -rf ~/.cache
          pnpm store prune
          rm -rf coverage/*

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Remove Playwright system deps after install
        run: |
          sudo rm -rf /usr/lib/x86_64-linux-gnu/libvulkan* || true
          sudo rm -rf /usr/lib/x86_64-linux-gnu/libgstreamer* || true
          sudo rm -rf /usr/lib/x86_64-linux-gnu/gstreamer* || true
          df -h

      - name: "Run Unit Tests: all workspaces with coverage"
        working-directory: ./
        run: |
          if [ github.actor != 'dependabot[bot]' ]; then
            pnpm run test:coverage
          else
            pnpm run test
          fi

      - name: "Upload coverage report to Codecov"
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: false
          directory: coverage
